config:
  buildmode: true
  no-perm: '&cNo permission!'
  staffmode: '&cYou need staffmode to do this.'
  gamemode: "&cYou can't change your gamemode"
  notfound: "&cThe specified player was not found."m

# Slots are from
# 0 to 8 (9 slots)
StaffItems:
  Vanish:
    EnableVanish:
      Name: "&3Vanish Off"
      Glow: true
      Material: "EMERALD_BLOCK"
      Slot: 8
      Lore:
        - '&eEdit in config.yml'
        - '&fSupports &c%player%'
        - '&4And &3C&bo&cl&9o&2r&as&7!'
    DisableVanish:
      Name: "&3Vanish On"
      Glow: true
      Material: "REDSTONE_BLOCK"
      # The slot is automatic updated when vanish updates
      Lore:
        - '&eEdit in config.yml'
        - '&fSupports &c%player%'
        - '&4And &3C&bo&cl&9o&2r&as&7!'

  RandomTeleport:
    Name: "&3Random Teleport"
    Glow: true
    Material: "REDSTONE_BLOCK"
    Slot: 2
    Lore:
      - '&eEdit in config.yml'
      - '&fSupports &c%player%'
      - '&4And &3C&bo&cl&9o&2r&as&7!'

  # WorldEdit wand is not configurable because it glitches.
  Wand:
    Enabled: true
    Slot: 0

  BuildMode:
    Name: "&3Build Mode"
    Glow: true
    Material: "DIAMOND"
    Slot: 4
    Lore:
      - '&eEdit in config.yml'
      - '&fSupports &c%player%'
      - '&4And &3C&bo&cl&9o&2r&as&7!'

Titles:
  BuildMode:
    Normal: "&bBuild Mode"
    Enabled: "&aHas been Enabled"
    Disabled: "&cHas been Disabled"

  StaffMode:
    Normal: "&bStaff Mode"
    Enabled: "&aHas been Enabled"
    Disabled: "&cHas been Disabled"

  Vanish:
    Normal: "&bVanish"
    Enabled: "&aHas been Enabled"
    Disabled: "&cHas been Disabled"

Messages:
  Staff:
    Leave: '&3[&bStaff&3] &a%player% &bLeft'
    Join: '&3[&bStaff&3] &a%player% &bJoin'

  StaffChat:
    Enabled: '&7[&bStaffChat&7] &aHas been Enabled'
    Disabled: '&7[&bStaffChat&7] &cHas been Disabled'
    Format: '&7[&bSC&7] &3%player%: &b%message%'

  Check:
    VanishedTrue: '&3%player% is vanished'
    VanishedFalse: '&3%player% is not vanished'
    ModModeTrue: '&3%player% is on mod mode'
    ModModeFalse: '&3%player% is not on mod mode'

  PluginInfo:
    Info1:
      - ''
      - '&b&l&k||&6 SModMode &b&l&k||'
      - ''
      - '&b&k|&6 ➥ &dAuthor: &5LSoofiaa / Apreciada &b&k|'
      - '&b&k|&6 ➥ &dVersion: &f%version% &b&k|'
      - ''

    Info2:
      - ''
      - '&b&l&k||&6 Commands &b&l&k||'
      - ''
      - '&b&k|&6 ➥ /staff &7(/mod, /staffmode) &b&k|'
      - '&b&k|&6 ➥ /staffchat &7(/sc) &b&k|'
      - '&b&k|&6 ➥ /build &b&k|'
      - ''

    Info3:
      - ''
      - '&b&l&k||&6 Permissions &b&l&k||'
      - ''
      - '&b&k|&6 ➥ /staff = &fsmodmode.staff &b&k|'
      - '&b&k|&6 ➥ /staffchat = &fsmodmode.staff &b&k|'
      - '&b&k|&6 ➥ /build = &fsmodmode.admin &b&k|'
      - ''